stages:
    - install
    - build
    - deploy

job1:
    stage: install
    tags:
        - java-cvm01
    script:
        - pwd
        - ls -l
        - npm install
        - ls -l

job2:
    stage: build
    tags:
        - java-cvm01
    script:
        - ls -l
        - npm run build:pro
        
job3:
    stage: deploy
    tags:
        - java-cvm01
    script:
        - id
