stages:
    - install
    - build
    - deploy

job1:
    stage: install
    tags:
        - java-cvm01
    script:
        - pwd
        - ls -la
        - npm install --registry=http://maven-repo.weiyankeji.cn/repository/npm-group/
        - ls -l

job2:
    stage: build
    tags:
        - java-cvm01
    script:
        - ls -l
        - npm run build:pro
        
job3:
    stage: deploy
    tags:
        - java-cvm01
    script:
        - id
