// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    404: typeof import("./src/components/ErrorMessage/404.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElButtonGroup: typeof import("element-plus/es")["ElButtonGroup"];
    ElCascaderPanel: typeof import("element-plus/es")["ElCascaderPanel"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSkeleton: typeof import("element-plus/es")["ElSkeleton"];
    ElSkeletonItem: typeof import("element-plus/es")["ElSkeletonItem"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElTree: typeof import("element-plus/es")["ElTree"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
